export const SET_USER = 'SET_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const SET_ERROR = 'SET_ERROR';
export const LOAD_TRANSCTION = 'LOAD_TRANSCTION'
export const CREATE_TRANSCTION = 'CREATE_TRANSCTION'
export const REMOVE_TRANSCTION = 'REMOVE_TRANSCTION'
export const UPDATE_TRNSCTION = 'UPDATE_TRNSCTION'